/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
import control.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import modelo.*;
import javax.swing.table.DefaultTableModel;

public class RegistroPersonaIU extends javax.swing.JFrame {
    // Atributos de Clase
    private GestorPersona gestorPersona;  
    // Una estructura de datos donde se almacena la informacion 
    // que se visualiza en un control de tipo JTable
    private DefaultTableModel modeloTablaPersona;
    private DefaultComboBoxModel modeloComboLugar;
    /**
     * Creates new form RegistroPersonaIU
     */
    public RegistroPersonaIU() {
        initComponents();
        // Crear el objeto para gestionar personas
        gestorPersona = new GestorPersona();
        // Crear el objeto modelo tabla
        modeloTablaPersona = new DefaultTableModel();
        // Personalizar las columnas
        modeloTablaPersona.addColumn("DNI");
        modeloTablaPersona.addColumn("Nombres");
        modeloTablaPersona.addColumn("Sexo");
        modeloTablaPersona.addColumn("Lugar Nacimiento");
        // Enlazar el modelo con el control JTable
        tablaPersona.setModel(modeloTablaPersona);
        actualizarTablaPersona(true);
        
        modeloComboLugar = new DefaultComboBoxModel();
        List<Lugar> lugares = gestorPersona.obtenerLugares();
        for (Lugar lugar : lugares) {
            modeloComboLugar.addElement(lugar);
        }
        cboLugarNacimiento.setModel(modeloComboLugar);
        
    }
    public void limpiarTablaPersona(){
        for (int i = modeloTablaPersona.getRowCount()-1; i >=0 ; i--) {
            modeloTablaPersona.removeRow(i);
        }
    }
    /*
    * Actualizar el modelo tabla
    */
    public void actualizarTablaPersona(boolean refrescar){
        if(refrescar){
            gestorPersona.refrescar();
        }
        // Limpiar la TablaPersona 
        limpiarTablaPersona();
        // Recuperar los datos de Gestion Persona
        for (int i = 0; i < gestorPersona.longitud(); i++) {
            String[] fila = new String[4]; // DNI, Nombres, Sexo, LugarNacimiento           
            int dni = gestorPersona.iesimo(i).getDni();
            // Convertir un entero a texto
            fila[0] = String.valueOf(dni);
            fila[1] = gestorPersona.iesimo(i).getNombres();
            fila[2] = String.valueOf(gestorPersona.iesimo(i).getSexo());
            fila[3] = gestorPersona.iesimo(i).getLugarNacimiento().getNombre();
            // Agregar un registro al modelo Tabla
            modeloTablaPersona.addRow(fila);
        }
        // Agragar los datos a la TablaPersona
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGrupoSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersona = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbSexoFemenino = new javax.swing.JRadioButton();
        rbSexoMasculino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cboLugarNacimiento = new javax.swing.JComboBox();
        btnOrdenarPorNombres = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnOrdenarPorCiudad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Registro de Personas");

        jLabel2.setText("DNI:");

        jLabel3.setText("Nombres:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        tablaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombres"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPersona);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo:"));

        rbGrupoSexo.add(rbSexoFemenino);
        rbSexoFemenino.setText("Femenino");

        rbGrupoSexo.add(rbSexoMasculino);
        rbSexoMasculino.setText("Masculino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbSexoMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(rbSexoFemenino)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSexoMasculino)
                    .addComponent(rbSexoFemenino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Lugar de Nacimiento:");

        btnOrdenarPorNombres.setText("Ordenar por Nombres");
        btnOrdenarPorNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPorNombresActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnOrdenarPorCiudad.setText("Ordenar por Ciudad");
        btnOrdenarPorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPorCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMostrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEliminar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnOrdenarPorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(btnOrdenarPorCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cboLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnOrdenarPorNombres)
                    .addComponent(btnOrdenarPorCiudad))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnMostrar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Que tenga un buen día.");
        System.exit(0);// Cerrar una Aplicacion
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // Recuperar los datos de la persona del Formulario
        int dni = Integer.valueOf(txtDNI.getText());
        String nombres = txtNombres.getText();
        //Recuperar el Sexo
        char sexo = '\000';
        if (rbSexoFemenino.isSelected()){
            sexo = 'F';
        }else{
            sexo = 'M';
        }
        // Recuperar el Lugar de nacimiento
        Lugar lugarNacimiento = (Lugar) cboLugarNacimiento.getSelectedItem();
        Persona objPersona = new Persona(dni,nombres,sexo,lugarNacimiento);
        // Registrar a la persona en el arreglo de Personas
        gestorPersona.agregar(objPersona);
        // Actualizar la tabla Persona en la Interfaz
        actualizarTablaPersona(true);
        JOptionPane.showMessageDialog(rootPane, "Se agrego con Exito..");        
        // Limpiar el Formulario
        txtDNI.setText("");
        txtNombres.setText("");
        txtDNI.requestFocus(); // Ubicar el cursos en la Caja de Texto
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, gestorPersona.mostrar());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Eliminar una persona del Registro
        // Preguntar si el usuario desea eliminar el registro
        int resultado = JOptionPane.
                showConfirmDialog(rootPane, "Desea eliminar?", "Eliminar Persona", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION){
            // Ubicar a la persona que se desea eliminar
            // Ubicar el indice que el usuario selecciono en la tablaPersona
            int numFila = tablaPersona.getSelectedRow();
            if (numFila>=0){//Selecciono una final
                // identificar el dni de la fila selecciona
                Object temp = modeloTablaPersona.getValueAt(numFila, 0); // obtener el valor de una celda
                int dni = Integer.valueOf(String.valueOf(temp));
                // Eliminar a la persona con el dni
                gestorPersona.eliminar(dni);
                // Actualizar la vista - Tabla donde se visualiza la informacion de las personas
                actualizarTablaPersona(true);
            }else{ // no selecciono una fila
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una fila");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnOrdenarPorNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPorNombresActionPerformed
        // Ordenar los datos por nombres
        gestorPersona.ordenarPorNombres();
        actualizarTablaPersona(false);
    }//GEN-LAST:event_btnOrdenarPorNombresActionPerformed

    private void btnOrdenarPorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPorCiudadActionPerformed
        // TODO add your handling code here:
        gestorPersona.ordenarPorCiudad();
        actualizarTablaPersona(false);
    }//GEN-LAST:event_btnOrdenarPorCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPersonaIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenarPorCiudad;
    private javax.swing.JButton btnOrdenarPorNombres;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboLugarNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup rbGrupoSexo;
    private javax.swing.JRadioButton rbSexoFemenino;
    private javax.swing.JRadioButton rbSexoMasculino;
    private javax.swing.JTable tablaPersona;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
